# Generated by Django 5.2.17 on 2026-08-26 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Categoría de evento',
                'verbose_name_plural': 'Categorías de evento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresarial', models.CharField(max_length=150)),
                ('nit', models.CharField(blank=True, max_length=30)),
                ('verificado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('lugar', models.CharField(max_length=200)),
                ('fecha_evento', models.DateTimeField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='BORRADOR', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.categoriaevento')),
            ],
            options={
                'ordering': ['fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('VIP', 'VIP'), ('PALCO', 'Palco'), ('PLATEA', 'Platea')], default='GENERAL', max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cupo', models.PositiveIntegerField()),
                ('vendidas', models.PositiveIntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='eventos.evento')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
    ]
